#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🟣🤘🏼 Checking the build of your project before pushing'

# Check Prettier standards
npm run build ||
(
  echo '⚙️❌⚙️❌ Build break! Don't Trust Murphy's Law. ❌⚙️❌⚙️
      Check what may have happened and, if you prefer, run the build in the terminal using the following command to check: npm run build.';
  false;
)

# If everything passes... Now we can commit
echo '💜🚀💜 Uhuu! Alright, now everything is ready to rock. You can celebrate for now hehe. I will push the changes. 💜🚀💜'

